[package]
name = "disc-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.11.1"
chrono = "0.4.38"
feed-rs = "2.1.1"
futures = "0.3.31"
json = "0.12.4"
reqwest = { version= "0.12.9", features = ["blocking"] }
serenity = "0.12.2"
tokio = "1.43.1"
